var baseContext = {
}
module.exports = {
	interface:{
		backend:{
			cloudEndpoint:"http://182.92.111.136:7366",
			localEndpoint:"http://localhost:7366"
		},
		qq:{
			loginEndpoint:'https://graph.qq.com/oauth2.0/show?which=Login&display=pc&response_type=code&client_id=100273020&redirect_uri=https%3A%2F%2Fplogin.m.jd.com%2Fcgi-bin%2Fml%2Fqqcallback%3Flsid%3Dglqwpjc1rlxhu3m0z6ingsl8zd6rvz7blx7agjc85apzdb0d&state=ij0ybm7b'
		}
	},
	service:{
		jd:{
			headerPCCookieName:"jd-pc-cookies",
			headerMobileCookieName:"jd-mobile-cookies"
		},
		arrangementStatus:{
			planned:'计划',
			running:'运行',
			cancelled:'终止',
			succeeded:'成功',
			failed:'失败',
			error:'错误'
		}
	},
	exception:{
		"REST3002":"无效二维码",
		"REST3005":"非登录状态"
	}
}
